package dk.kmd.drools.applicant

rule "Is of valid age"
	salience 5
	when
	    $a : Applicant( age >= 18, valid == false)
	then
		modify( $a ) { setValid( true ) };	    
		System.out.println("Set valid true");
end

rule "Print not valid"
	salience -5
	when 
		$a : Applicant( valid == false )
	then
		System.out.println("NOT valid age : " + $a.getAge());
end	

rule "Print valid"
	salience -5
	when 
		$a : Applicant( valid == true );
	then
		System.out.println("Valid age : " + $a.getAge());
end	

